#!/usr/bin/env python
# -- Content-Encoding: UTF-8 --
"""
Extracts the release notes of a version from ``docs/changelog.md``.

The changelog is the single source of truth for what a release contains: the
notes shown on the GitHub release page are generated from it rather than
written a second time by hand.

The script also refuses to produce notes for a release whose date is still
``Unreleased``, which makes it the last guard before a tag is published.

:author: Thomas Calmant
:copyright: Copyright 2026, Thomas Calmant
:license: Apache License 2.0
:version: 3.2.2

..

    Copyright 2026 Thomas Calmant

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import argparse
import pathlib
import re
import sys

# Module version
__version_info__ = (3, 2, 2)
__version__ = ".".join(str(x) for x in __version_info__)

# Documentation strings format
__docformat__ = "restructuredtext en"

#: Root of the repository, i.e. the parent of ``.github``
ROOT = pathlib.Path(__file__).resolve().parents[2]

#: The MyST admonition holding the release date, as written in the changelog
DATE_ADMONITION_PATTERN = re.compile(
    r"^:::\{admonition\}\s*Release Date\s*$.*?^:::\s*$",
    re.MULTILINE | re.DOTALL,
)

#: The date itself, inside the admonition
DATE_VALUE_PATTERN = re.compile(r"^(?!:)(\S.*)$", re.MULTILINE)

#: Documentation of the release notes, on Read the Docs
CHANGELOG_URL = "https://ipopo.readthedocs.io/en/latest/changelog.html"

#: Footer explaining how to check the integrity of the published artifacts
VERIFICATION_FOOTER = """
## Verifying this release

Each artifact published on PyPI carries a [PEP 740](https://peps.python.org/pep-0740/)
attestation, generated by the `publish.yml` workflow through PyPI Trusted Publishing:
no long-lived token is involved, and the attestation is visible on the PyPI page of
each file.

The same artifacts are attached below, together with their CycloneDX Software Bill of
Materials, and are covered by a SLSA build provenance attestation:

```bash
gh attestation verify <downloaded file> --repo {repository}
git tag -v {tag}
```
"""


def find_section(changelog: str, version: str) -> str:
    """
    Extracts the section of the changelog describing the given version

    :param changelog: Content of the changelog
    :param version: Version to look for
    :return: The content of the section, without its title
    :raise KeyError: No section found for that version
    """
    title = f"## iPOPO {version}"
    lines = changelog.splitlines()
    try:
        start = next(idx for idx, line in enumerate(lines) if line.strip() == title)
    except StopIteration:
        raise KeyError(f"No '{title}' section in the changelog") from None

    end = next(
        (idx for idx, line in enumerate(lines[start + 1 :], start + 1) if line.startswith("## ")),
        len(lines),
    )
    return "\n".join(lines[start + 1 : end]).strip()


def split_date(section: str) -> tuple[str, str]:
    """
    Separates the release date from the body of a changelog section

    :param section: Content of a changelog section
    :return: A (date, body) tuple
    :raise ValueError: The section has no release date admonition
    """
    match = DATE_ADMONITION_PATTERN.search(section)
    if match is None:
        raise ValueError("No 'Release Date' admonition in the section")

    # Skip the ':::{admonition}' and ':class:' lines to reach the date itself
    inner = match.group(0).splitlines()[2:-1]
    dates = DATE_VALUE_PATTERN.findall("\n".join(inner))
    if not dates:
        raise ValueError("The 'Release Date' admonition is empty")

    body = (section[: match.start()] + section[match.end() :]).strip()
    return dates[0].strip(), body


def main() -> int:
    """
    Script entry point

    :return: The exit code of the script
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="Version to extract, e.g. 3.2.2")
    parser.add_argument("-o", "--output", help="File to write the notes to (default: stdout)")
    parser.add_argument(
        "--repository",
        default="tcalmant/ipopo",
        help="GitHub repository, used in the verification instructions",
    )
    parser.add_argument(
        "--changelog",
        default=str(ROOT / "docs" / "changelog.md"),
        help="Path to the changelog",
    )
    args = parser.parse_args()

    changelog = pathlib.Path(args.changelog).read_text(encoding="utf-8")
    try:
        section = find_section(changelog, args.version)
        date, body = split_date(section)
    except (KeyError, ValueError) as ex:
        print(f"::error::{ex}", file=sys.stderr)
        return 1

    if date.lower() == "unreleased":
        print(
            f"::error::iPOPO {args.version} is still marked as 'Unreleased' in the changelog",
            file=sys.stderr,
        )
        return 1

    header = (
        f"Released on {date}. The complete release notes are available on [Read the Docs]({CHANGELOG_URL})."
    )
    notes = "\n".join(
        (
            header,
            "",
            body,
            "",
            VERIFICATION_FOOTER.format(repository=args.repository, tag=args.version).strip(),
            "",
        )
    )

    if args.output:
        pathlib.Path(args.output).write_text(notes, encoding="utf-8")
    else:
        sys.stdout.write(notes)
    return 0


if __name__ == "__main__":
    sys.exit(main())
