# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hellomsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hellomsg.proto',
  package='org.eclipse.ecf.examples.protobuf.hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0ehellomsg.proto\x12\'org.eclipse.ecf.examples.protobuf.hello\"P\n\x0fHelloMsgContent\x12\t\n\x01h\x18\x01 \x01(\t\x12\t\n\x01\x66\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x10\n\x08hellomsg\x18\x04 \x01(\t\x12\t\n\x01x\x18\x05 \x03(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOMSGCONTENT = _descriptor.Descriptor(
  name='HelloMsgContent',
  full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='h', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.h', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.f', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hellomsg', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.hellomsg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent.x', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['HelloMsgContent'] = _HELLOMSGCONTENT

HelloMsgContent = _reflection.GeneratedProtocolMessageType('HelloMsgContent', (_message.Message,), dict(
  DESCRIPTOR = _HELLOMSGCONTENT,
  __module__ = 'hellomsg_pb2'
  # @@protoc_insertion_point(class_scope:org.eclipse.ecf.examples.protobuf.hello.HelloMsgContent)
  ))
_sym_db.RegisterMessage(HelloMsgContent)


# @@protoc_insertion_point(module_scope)
