#!/usr/bin/env python3
# -- Content-Encoding: UTF-8 --
"""
Checks the explicit public API declaration (``__all__``) of the Pelix modules

:license: Apache License 2.0
"""

import importlib
import inspect
import pkgutil
import types
import unittest
from collections.abc import Iterator

import pelix
from pelix.constants import ACTIVATOR, ACTIVATOR_LEGACY
from pelix.ipopo.constants import IPOPO_FACTORY_CONTEXT

# ------------------------------------------------------------------------------

__version_info__ = (3, 2, 3)
__version__ = ".".join(str(x) for x in __version_info__)

# ------------------------------------------------------------------------------

# Packages not checked at all
IGNORED_PACKAGES = (
    # Generated by the protobuf compiler
    "pelix.rsa.providers.discovery.etcd3.rpc",
)

# Modules not imported: importing them has side effects
IGNORED_MODULES = {
    # Runs the shell
    "pelix.shell.__main__",
}

# Modules allowed to lack __all__ for now
MISSING_ALL_EXEMPTIONS: set[str] = set()

# Modules whose public classes and functions are not checked against __all__
PUBLIC_NAMES_EXEMPTIONS: set[str] = set()

# Public classes and functions intentionally left out of __all__, per module.
# Bundle activators and iPOPO component factories are detected and skipped
# automatically: they are instantiated by the framework, not used directly.
EXCLUDED_NAMES: dict[str, set[str]] = {
    # Internal inet_pton shim, defined differently on Windows
    "pelix.remote.discovery.multicast": {"pton"},
}

# ------------------------------------------------------------------------------


def _walk_modules() -> Iterator[types.ModuleType]:
    """
    Imports and yields all the Pelix modules which can be loaded in this environment
    """
    names: list[str] = []
    # Packages which can't be imported (missing optional dependency) are skipped
    for info in pkgutil.walk_packages(pelix.__path__, "pelix.", onerror=lambda _: None):
        names.append(info.name)

    for name in ["pelix", *names]:
        if name in IGNORED_MODULES or any(
            name == pkg or name.startswith(pkg + ".") for pkg in IGNORED_PACKAGES
        ):
            continue

        try:
            yield importlib.import_module(name)
        except ImportError:
            # Optional dependency not installed
            continue


def _is_activator(module: types.ModuleType, obj: object) -> bool:
    """
    Checks if the given object is the class of the module bundle activator
    """
    for attr in (ACTIVATOR, ACTIVATOR_LEGACY):
        activator = getattr(module, attr, None)
        if activator is not None and (activator is obj or type(activator) is obj):
            return True
    return False


def _is_component_factory(obj: object) -> bool:
    """
    Checks if the given object is a class manipulated as an iPOPO component factory
    """
    if not inspect.isclass(obj):
        return False

    # Look only at the class itself, not at the context inherited from a parent factory
    context = vars(obj).get(IPOPO_FACTORY_CONTEXT)
    return context is not None and bool(getattr(context, "name", None))


class AllDeclarationsTest(unittest.TestCase):
    """
    Checks the ``__all__`` declaration of every Pelix module
    """

    @classmethod
    def setUpClass(cls) -> None:
        cls.modules = list(_walk_modules())

    def test_modules_found(self) -> None:
        """
        Sanity check of the module discovery
        """
        names = {module.__name__ for module in self.modules}
        for name in ("pelix", "pelix.framework", "pelix.ipopo.decorators", "pelix.shell.core"):
            self.assertIn(name, names)

    def test_all_declared(self) -> None:
        """
        Every module must declare __all__, as a sequence of unique existing names
        """
        for module in self.modules:
            name = module.__name__
            with self.subTest(module=name):
                if not hasattr(module, "__all__"):
                    if name not in MISSING_ALL_EXEMPTIONS:
                        self.fail(f"{name} has no __all__")
                    continue

                exported = module.__all__
                self.assertIsInstance(exported, (list, tuple))
                for exported_name in exported:
                    self.assertIsInstance(exported_name, str)
                    self.assertTrue(
                        hasattr(module, exported_name),
                        f"{name}.__all__ references a missing name: {exported_name}",
                    )

                duplicates = sorted({x for x in exported if list(exported).count(x) > 1})
                self.assertFalse(duplicates, f"Duplicates in {name}.__all__: {duplicates}")

    def test_public_names_exported(self) -> None:
        """
        Public classes and functions defined in a module must be listed in its __all__
        """
        for module in self.modules:
            name = module.__name__
            if not hasattr(module, "__all__") or name in PUBLIC_NAMES_EXEMPTIONS:
                continue

            with self.subTest(module=name):
                exported = set(module.__all__)
                excluded = EXCLUDED_NAMES.get(name, set())
                missing: list[str] = []
                for attr_name, obj in vars(module).items():
                    if (
                        attr_name.startswith("_")
                        or not (inspect.isclass(obj) or inspect.isfunction(obj))
                        or getattr(obj, "__module__", None) != name
                        or attr_name in exported
                        or attr_name in excluded
                        or _is_activator(module, obj)
                        or _is_component_factory(obj)
                    ):
                        continue
                    missing.append(attr_name)

                self.assertFalse(missing, f"Public names missing from {name}.__all__: {sorted(missing)}")

    def test_exclusions_up_to_date(self) -> None:
        """
        The exclusion mapping must not reference exported or unknown names
        """
        modules = {module.__name__: module for module in self.modules}
        for name, excluded in EXCLUDED_NAMES.items():
            module = modules.get(name)
            if module is None:
                # Not importable in this environment
                continue

            with self.subTest(module=name):
                for excluded_name in excluded:
                    self.assertTrue(hasattr(module, excluded_name), f"Unknown name: {excluded_name}")
                    self.assertNotIn(excluded_name, getattr(module, "__all__", ()))


# ------------------------------------------------------------------------------

if __name__ == "__main__":
    unittest.main()
