"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers

if sys.version_info >= (3, 11):
    from typing import Never as _Never
    from typing import TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias

    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RaftAttributes(_message.Message):
    """RaftAttributes represents the raft related attributes of an etcd member."""

    DESCRIPTOR: _descriptor.Descriptor

    PEER_URLS_FIELD_NUMBER: _builtins.int
    IS_LEARNER_FIELD_NUMBER: _builtins.int
    is_learner: _builtins.bool
    """isLearner indicates if the member is raft learner."""
    @_builtins.property
    def peer_urls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """peerURLs is the list of peers in the raft cluster."""

    def __init__(
        self,
        *,
        peer_urls: _abc.Iterable[_builtins.str] | None = ...,
        is_learner: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_learner", b"is_learner", "peer_urls", b"peer_urls"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RaftAttributes: _TypeAlias = RaftAttributes  # noqa: Y015

@_typing.final
class Attributes(_message.Message):
    """Attributes represents all the non-raft related attributes of an etcd member."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    CLIENT_URLS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def client_urls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        client_urls: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_urls", b"client_urls", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Attributes: _TypeAlias = Attributes  # noqa: Y015

@_typing.final
class Member(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    RAFT_ATTRIBUTES_FIELD_NUMBER: _builtins.int
    MEMBER_ATTRIBUTES_FIELD_NUMBER: _builtins.int
    ID: _builtins.int
    @_builtins.property
    def raft_attributes(self) -> Global___RaftAttributes: ...
    @_builtins.property
    def member_attributes(self) -> Global___Attributes: ...
    def __init__(
        self,
        *,
        ID: _builtins.int = ...,
        raft_attributes: Global___RaftAttributes | None = ...,
        member_attributes: Global___Attributes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "member_attributes", b"member_attributes", "raft_attributes", b"raft_attributes"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "ID", b"ID", "member_attributes", b"member_attributes", "raft_attributes", b"raft_attributes"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Member: _TypeAlias = Member  # noqa: Y015

@_typing.final
class ClusterVersionSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VER_FIELD_NUMBER: _builtins.int
    ver: _builtins.str
    def __init__(
        self,
        *,
        ver: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ver", b"ver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClusterVersionSetRequest: _TypeAlias = ClusterVersionSetRequest  # noqa: Y015

@_typing.final
class ClusterMemberAttrSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MEMBER_ID_FIELD_NUMBER: _builtins.int
    MEMBER_ATTRIBUTES_FIELD_NUMBER: _builtins.int
    member_ID: _builtins.int
    @_builtins.property
    def member_attributes(self) -> Global___Attributes: ...
    def __init__(
        self,
        *,
        member_ID: _builtins.int = ...,
        member_attributes: Global___Attributes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["member_attributes", b"member_attributes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "member_ID", b"member_ID", "member_attributes", b"member_attributes"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClusterMemberAttrSetRequest: _TypeAlias = ClusterMemberAttrSetRequest  # noqa: Y015

@_typing.final
class DowngradeInfoSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    VER_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    ver: _builtins.str
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        ver: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "ver", b"ver"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DowngradeInfoSetRequest: _TypeAlias = DowngradeInfoSetRequest  # noqa: Y015
