"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserAddOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NO_PASSWORD_FIELD_NUMBER: _builtins.int
    no_password: _builtins.bool
    def __init__(
        self,
        *,
        no_password: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["no_password", b"no_password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UserAddOptions: _TypeAlias = UserAddOptions  # noqa: Y015

@_typing.final
class User(_message.Message):
    """User is a single entry in the bucket authUsers"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    name: _builtins.bytes
    password: _builtins.bytes
    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def options(self) -> Global___UserAddOptions: ...
    def __init__(
        self,
        *,
        name: _builtins.bytes = ...,
        password: _builtins.bytes = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        options: Global___UserAddOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "options", b"options", "password", b"password", "roles", b"roles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class Permission(_message.Message):
    """Permission is a single entity"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Permission._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        READ: Permission._Type.ValueType  # 0
        WRITE: Permission._Type.ValueType  # 1
        READWRITE: Permission._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    READ: Permission.Type.ValueType  # 0
    WRITE: Permission.Type.ValueType  # 1
    READWRITE: Permission.Type.ValueType  # 2

    PERMTYPE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    RANGE_END_FIELD_NUMBER: _builtins.int
    permType: Global___Permission.Type.ValueType
    key: _builtins.bytes
    range_end: _builtins.bytes
    def __init__(
        self,
        *,
        permType: Global___Permission.Type.ValueType = ...,
        key: _builtins.bytes = ...,
        range_end: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "permType", b"permType", "range_end", b"range_end"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Permission: _TypeAlias = Permission  # noqa: Y015

@_typing.final
class Role(_message.Message):
    """Role is a single entry in the bucket authRoles"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    KEYPERMISSION_FIELD_NUMBER: _builtins.int
    name: _builtins.bytes
    @_builtins.property
    def keyPermission(self) -> _containers.RepeatedCompositeFieldContainer[Global___Permission]: ...
    def __init__(
        self,
        *,
        name: _builtins.bytes = ...,
        keyPermission: _abc.Iterable[Global___Permission] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keyPermission", b"keyPermission", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Role: _TypeAlias = Role  # noqa: Y015
