"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 11):
    from typing import Never as _Never
    from typing import TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias

    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class KeyValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    CREATE_REVISION_FIELD_NUMBER: _builtins.int
    MOD_REVISION_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    LEASE_FIELD_NUMBER: _builtins.int
    key: _builtins.bytes
    """key is the key in bytes. An empty key is not allowed."""
    create_revision: _builtins.int
    """create_revision is the revision of last creation on this key."""
    mod_revision: _builtins.int
    """mod_revision is the revision of last modification on this key."""
    version: _builtins.int
    """version is the version of the key. A deletion resets
    the version to zero and any modification of the key
    increases its version.
    """
    value: _builtins.bytes
    """value is the value held by the key, in bytes."""
    lease: _builtins.int
    """lease is the ID of the lease that attached to key.
    When the attached lease expires, the key will be deleted.
    If lease is 0, then no lease is attached to the key.
    """
    def __init__(
        self,
        *,
        key: _builtins.bytes = ...,
        create_revision: _builtins.int = ...,
        mod_revision: _builtins.int = ...,
        version: _builtins.int = ...,
        value: _builtins.bytes = ...,
        lease: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["create_revision", b"create_revision", "key", b"key", "lease", b"lease", "mod_revision", b"mod_revision", "value", b"value", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KeyValue: _TypeAlias = KeyValue  # noqa: Y015

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _EventType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Event._EventType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        PUT: Event._EventType.ValueType  # 0
        DELETE: Event._EventType.ValueType  # 1

    class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...
    PUT: Event.EventType.ValueType  # 0
    DELETE: Event.EventType.ValueType  # 1

    TYPE_FIELD_NUMBER: _builtins.int
    KV_FIELD_NUMBER: _builtins.int
    PREV_KV_FIELD_NUMBER: _builtins.int
    type: Global___Event.EventType.ValueType
    """type is the kind of event. If type is a PUT, it indicates
    new data has been stored to the key. If type is a DELETE,
    it indicates the key was deleted.
    """
    @_builtins.property
    def kv(self) -> Global___KeyValue:
        """kv holds the KeyValue for the event.
        A PUT event contains current kv pair.
        A PUT event with kv.Version=1 indicates the creation of a key.
        A DELETE/EXPIRE event contains the deleted key with
        its modification revision set to the revision of deletion.
        """

    @_builtins.property
    def prev_kv(self) -> Global___KeyValue:
        """prev_kv holds the key-value pair before the event happens."""

    def __init__(
        self,
        *,
        type: Global___Event.EventType.ValueType = ...,
        kv: Global___KeyValue | None = ...,
        prev_kv: Global___KeyValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kv", b"kv", "prev_kv", b"prev_kv"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kv", b"kv", "prev_kv", b"prev_kv", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015
