# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pelix/rsa/providers/discovery/etcd3/rpc/kv.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 2, "", "pelix/rsa/providers/discovery/etcd3/rpc/kv.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n0pelix/rsa/providers/discovery/etcd3/rpc/kv.proto\x12\x06mvccpb"\xae\x01\n\x08KeyValue\x12\x10\n\x03key\x18\x01 \x01(\x0cR\x03key\x12\'\n\x0f\x63reate_revision\x18\x02 \x01(\x03R\x0e\x63reateRevision\x12!\n\x0cmod_revision\x18\x03 \x01(\x03R\x0bmodRevision\x12\x18\n\x07version\x18\x04 \x01(\x03R\x07version\x12\x14\n\x05value\x18\x05 \x01(\x0cR\x05value\x12\x14\n\x05lease\x18\x06 \x01(\x03R\x05lease"\xa3\x01\n\x05\x45vent\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x17.mvccpb.Event.EventTypeR\x04type\x12 \n\x02kv\x18\x02 \x01(\x0b\x32\x10.mvccpb.KeyValueR\x02kv\x12)\n\x07prev_kv\x18\x03 \x01(\x0b\x32\x10.mvccpb.KeyValueR\x06prevKv" \n\tEventType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42M\n\ncom.mvccpbB\x07KvProtoP\x01\xa2\x02\x03MXX\xaa\x02\x06Mvccpb\xca\x02\x06Mvccpb\xe2\x02\x12Mvccpb\\GPBMetadata\xea\x02\x06Mvccpbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "pelix.rsa.providers.discovery.etcd3.rpc.kv_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\ncom.mvccpbB\007KvProtoP\001\242\002\003MXX\252\002\006Mvccpb\312\002\006Mvccpb\342\002\022Mvccpb\\GPBMetadata\352\002\006Mvccpb"
    _globals["_KEYVALUE"]._serialized_start = 61
    _globals["_KEYVALUE"]._serialized_end = 235
    _globals["_EVENT"]._serialized_start = 238
    _globals["_EVENT"]._serialized_end = 401
    _globals["_EVENT_EVENTTYPE"]._serialized_start = 369
    _globals["_EVENT_EVENTTYPE"]._serialized_end = 401
# @@protoc_insertion_point(module_scope)
