# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pelix/rsa/providers/discovery/etcd3/rpc/membership.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'pelix/rsa/providers/discovery/etcd3/rpc/membership.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8pelix/rsa/providers/discovery/etcd3/rpc/membership.proto\x12\x0cmembershippb\x1a\x35pelix/rsa/providers/discovery/etcd3/rpc/version.proto\"U\n\x0eRaftAttributes\x12\x1b\n\tpeer_urls\x18\x01 \x03(\tR\x08peerUrls\x12\x1d\n\nis_learner\x18\x02 \x01(\x08R\tisLearner:\x07\x82\xb5\x18\x03\x33.5\"J\n\nAttributes\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\x0b\x63lient_urls\x18\x02 \x03(\tR\nclientUrls:\x07\x82\xb5\x18\x03\x33.5\"\xaf\x01\n\x06Member\x12\x0e\n\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x45\n\x0fraft_attributes\x18\x02 \x01(\x0b\x32\x1c.membershippb.RaftAttributesR\x0eraftAttributes\x12\x45\n\x11member_attributes\x18\x03 \x01(\x0b\x32\x18.membershippb.AttributesR\x10memberAttributes:\x07\x82\xb5\x18\x03\x33.5\"5\n\x18\x43lusterVersionSetRequest\x12\x10\n\x03ver\x18\x01 \x01(\tR\x03ver:\x07\x82\xb5\x18\x03\x33.5\"\x8a\x01\n\x1b\x43lusterMemberAttrSetRequest\x12\x1b\n\tmember_ID\x18\x01 \x01(\x04R\x08memberID\x12\x45\n\x11member_attributes\x18\x02 \x01(\x0b\x32\x18.membershippb.AttributesR\x10memberAttributes:\x07\x82\xb5\x18\x03\x33.5\"N\n\x17\x44owngradeInfoSetRequest\x12\x18\n\x07\x65nabled\x18\x01 \x01(\x08R\x07\x65nabled\x12\x10\n\x03ver\x18\x02 \x01(\tR\x03ver:\x07\x82\xb5\x18\x03\x33.5Bs\n\x10\x63om.membershippbB\x0fMembershipProtoP\x01\xa2\x02\x03MXX\xaa\x02\x0cMembershippb\xca\x02\x0cMembershippb\xe2\x02\x18Membershippb\\GPBMetadata\xea\x02\x0cMembershippbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pelix.rsa.providers.discovery.etcd3.rpc.membership_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.membershippbB\017MembershipProtoP\001\242\002\003MXX\252\002\014Membershippb\312\002\014Membershippb\342\002\030Membershippb\\GPBMetadata\352\002\014Membershippb'
  _globals['_RAFTATTRIBUTES']._loaded_options = None
  _globals['_RAFTATTRIBUTES']._serialized_options = b'\202\265\030\0033.5'
  _globals['_ATTRIBUTES']._loaded_options = None
  _globals['_ATTRIBUTES']._serialized_options = b'\202\265\030\0033.5'
  _globals['_MEMBER']._loaded_options = None
  _globals['_MEMBER']._serialized_options = b'\202\265\030\0033.5'
  _globals['_CLUSTERVERSIONSETREQUEST']._loaded_options = None
  _globals['_CLUSTERVERSIONSETREQUEST']._serialized_options = b'\202\265\030\0033.5'
  _globals['_CLUSTERMEMBERATTRSETREQUEST']._loaded_options = None
  _globals['_CLUSTERMEMBERATTRSETREQUEST']._serialized_options = b'\202\265\030\0033.5'
  _globals['_DOWNGRADEINFOSETREQUEST']._loaded_options = None
  _globals['_DOWNGRADEINFOSETREQUEST']._serialized_options = b'\202\265\030\0033.5'
  _globals['_RAFTATTRIBUTES']._serialized_start=129
  _globals['_RAFTATTRIBUTES']._serialized_end=214
  _globals['_ATTRIBUTES']._serialized_start=216
  _globals['_ATTRIBUTES']._serialized_end=290
  _globals['_MEMBER']._serialized_start=293
  _globals['_MEMBER']._serialized_end=468
  _globals['_CLUSTERVERSIONSETREQUEST']._serialized_start=470
  _globals['_CLUSTERVERSIONSETREQUEST']._serialized_end=523
  _globals['_CLUSTERMEMBERATTRSETREQUEST']._serialized_start=526
  _globals['_CLUSTERMEMBERATTRSETREQUEST']._serialized_end=664
  _globals['_DOWNGRADEINFOSETREQUEST']._serialized_start=666
  _globals['_DOWNGRADEINFOSETREQUEST']._serialized_end=744
# @@protoc_insertion_point(module_scope)
