# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pelix/rsa/providers/discovery/etcd3/rpc/version.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'pelix/rsa/providers/discovery/etcd3/rpc/version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5pelix/rsa/providers/discovery/etcd3/rpc/version.proto\x12\tversionpb\x1a google/protobuf/descriptor.proto:N\n\x10\x65tcd_version_msg\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\tR\x0e\x65tcdVersionMsg\x88\x01\x01:P\n\x12\x65tcd_version_field\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\tR\x10\x65tcdVersionField\x88\x01\x01:M\n\x11\x65tcd_version_enum\x12\x1c.google.protobuf.EnumOptions\x18\xd2\x86\x03 \x01(\tR\x0f\x65tcdVersionEnum\x88\x01\x01:]\n\x17\x65tcd_version_enum_value\x12!.google.protobuf.EnumValueOptions\x18\xd3\x86\x03 \x01(\tR\x14\x65tcdVersionEnumValue\x88\x01\x01\x42\x61\n\rcom.versionpbB\x0cVersionProtoP\x01\xa2\x02\x03VXX\xaa\x02\tVersionpb\xca\x02\tVersionpb\xe2\x02\x15Versionpb\\GPBMetadata\xea\x02\tVersionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pelix.rsa.providers.discovery.etcd3.rpc.version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.versionpbB\014VersionProtoP\001\242\002\003VXX\252\002\tVersionpb\312\002\tVersionpb\342\002\025Versionpb\\GPBMetadata\352\002\tVersionpb'
# @@protoc_insertion_point(module_scope)
