User's Guide
============

This chapter details how to install and use iPOPO.

.. toctree::
   :maxdepth: 2
   
   foreword
   installation
   quickstart
   tutorials/index
   refcards/index

API Reference
=============

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api


Additional Notes
================

Design notes, legal information and changelog are here for the
interested.

.. toctree::
   :maxdepth: 2
   
   changelog
   license
